*This do file adds in Gleditsch and Ward country codes for datasets that identify observations
*by country name only.  It is accurate to the best of my knowledge, and is updated every time I
*have to add a new spelling.  Please contact me if you find any errors or omissions.
*Clayton Thyne, University of Kentucky, clayton.thyne@uky.edu

gen ccode=.
label var ccode "COW ccodes"
replace ccode= 700 if country=="Afghanistan"
replace ccode= 700 if country=="Afganistan"
replace ccode= 339 if country=="Albania"
replace ccode= 615 if country=="Algeria"
replace ccode= 232 if country=="Andorra"
replace ccode= 540 if country=="Angola"
replace ccode= 58 if country=="Antigua and Barbuda"
replace ccode= 58 if country=="Antigua & Barbados"
replace ccode= 58 if country=="Antigua and Barbados"
replace ccode= 58 if country==" Antigua & Barb."
replace ccode= 58 if country==" Antigua & Barbuda"
replace ccode= 58 if country=="Antigua"
replace ccode= 58 if country=="Antigua & Barbuda"
replace ccode= 160 if country=="Argentina"
replace ccode= 371 if country=="Armenia"
replace ccode= 900 if country=="Australia"
replace ccode= 305 if country=="Austria"
replace ccode= 300 if country=="Austria-Hungary"
replace ccode= 373 if country=="Azerbaijan"
replace ccode= 267 if country=="Baden"
replace ccode= 31 if country=="Bahamas, The"
replace ccode= 31 if country=="Bahamas, The"
replace ccode= 31 if country=="Bahamas"
replace ccode= 31 if country=="The Bahamas"
replace ccode= 692 if country=="Bahrein"
replace ccode= 692 if country=="Bahrain"
replace ccode= 771 if country=="Bangladesh"
replace ccode= 53 if country=="Barbados"
replace ccode= 245 if country=="Bavaria"
replace ccode= 370 if country=="Belarus"
replace ccode= 370 if country=="Byelorussia"
replace ccode= 211 if country=="Belgium"
replace ccode= 80 if country=="Belize"
replace ccode= 434 if country=="Benin"
replace ccode= 760 if country=="Bhutan"
replace ccode= 145 if country=="Bolivia"
replace ccode= 145 if country=="Bolivia (Plurinational State of)"
replace ccode= 346 if country=="Bosnia/Herzogovina"
replace ccode= 346 if country=="Bosnia-Herzogovina"
replace ccode= 346 if country=="Bosnia-Herzegovina"
replace ccode= 346 if country=="Bosnia andHerzegovina"
replace ccode= 346 if country=="Bosnia"
replace ccode= 346 if country=="Yugoslavia Bosnia"
replace ccode= 346 if country=="Bosnia-Herz"
replace ccode= 346 if country=="Bosnia & Herzegovina"
replace ccode= 346 if country=="Bosnia and Herzegovina"
replace ccode= 571 if country=="Bophutatswana"
replace ccode= 571 if country=="Botswana"
replace ccode= 571 if country=="Bostwana"
replace ccode= 140 if country=="Brazil"
replace ccode= 835 if country=="Brunei"
replace ccode= 835 if country=="Brunei Darussalam"
replace ccode= 355 if country=="Bulgaria"
replace ccode= 439 if country=="Burkina Faso"
replace ccode= 439 if country=="BurkinaFaso"
replace ccode= 439 if country=="Burkina Fasso"
replace ccode= 439 if country=="Burkina Fasso (Upper Volta)"
replace ccode= 516 if country=="Burundi"
replace ccode= 811 if country=="Cambodia"
replace ccode= 811 if country=="Cambodia (Kampuchea)"
replace ccode= 471 if country=="Cameroun"
replace ccode= 471 if country=="Cameroon"
replace ccode= 20 if country=="Canada"
replace ccode= 402 if country=="Cape Verde"
replace ccode= 402 if country=="Cape verde"
replace ccode= 402 if country=="C. Verde Is."
replace ccode= 402 if country=="Cabo Verde"
replace ccode= 482 if country=="Central African Republic"
replace ccode= 482 if country=="CentralAfricanRepublic"
replace ccode= 482 if country=="Central Africa"
replace ccode= 482 if country=="Central African Rep."
replace ccode= 482 if country=="Central Afr. R."
replace ccode= 482 if country=="Cent. Af. Rep."
replace ccode= 482 if country=="Cen African Rep"
replace ccode= 482 if country=="Central African Rep"
replace ccode= 483 if country=="Chad"
replace ccode= 155 if country=="Chile"
replace ccode= 710 if country=="China"
replace ccode= 710 if country=="China, People's Republic of"
replace ccode= 710 if country=="China (P.R.C.)"
replace ccode= 710 if country=="PRC"
replace ccode= 710 if country=="China, P.R.: Mainland"
replace ccode= 100 if country=="Colombia"
replace ccode= 581 if country=="Comoros"
replace ccode= 581 if country=="Comor Is."
replace ccode= 581 if country=="Comoro Is."
replace ccode= 484 if country=="Congo, Rep."
replace ccode= 484 if country=="Congo (Republic of Congo)"
replace ccode= 484 if country=="Congo Rep. (Brazzaville)"
replace ccode= 484 if country=="Congo (Brazzaville)"
replace ccode= 484 if country=="Congo-Brazzaville"
replace ccode= 484 if country=="Congo"
replace ccode= 484 if country=="Republic of the Congo"
replace ccode= 484 if country=="Republic of Congo"
replace ccode= 484 if country=="Congo, Republic of"
replace ccode= 484 if country=="Congo Brazzaville"
replace ccode= 484 if country=="Congo-Brz"
replace ccode= 484 if country=="Congo (Brazzaville, Republic of Congo)"
replace ccode= 484 if country=="Congo, Republic Of"
replace ccode= 484 if country=="CongoÂ¬â€ (Brazzaville)"
replace ccode= 490 if country=="Congo, DR - Zaire"
replace ccode= 490 if country=="Congo DR (Zaire)"
replace ccode= 490 if country=="Congo, DRC (formerly Zaire)"
replace ccode= 490 if country=="DemocraticRep.oftheCongo"
replace ccode= 490 if country=="Democratic Republic of the Congo"
replace ccode= 490 if country=="Democratic Republic of Congo"
replace ccode= 490 if country=="Congo, Democratic Republic of"
replace ccode= 490 if country=="Congo (Kinshasa)"
replace ccode= 490 if country=="Democratic Republic of the Congo (Zaire, Congo-Kinshasha)"
replace ccode= 490 if country=="Congo (DRC)"
replace ccode= 490 if country=="Congo, the Democratic Republic of the"
replace ccode= 490 if country=="D R Congo"
replace ccode= 490 if country=="Congo, (Kinshasa)"
replace ccode=490 if country=="Congo, Dem. Rep."
replace ccode=490 if country=="Zaire"
replace ccode=490 if country=="Zaire (Democ Republic Congo)"
replace ccode= 490 if country=="Congo, Dem. Rep, Of"
replace ccode= 490 if country=="Congo/Zaire"
replace ccode=490 if country=="Congo Kinshasa"
replace ccode= 94 if country=="Costa Rica"
replace ccode= 437 if country=="Ivory Coast"
replace ccode= 437 if country=="Cï¿½te d'Ivoire"
replace ccode= 437 if country=="C?te d'Ivoire"
replace ccode= 437 if country=="C?ted'Ivoire"
replace ccode= 437 if country=="Code d'Ivoire"
replace ccode= 437 if country=="C?te d'Ivoire"
replace ccode= 437 if country=="Cote d'Ivoire"
replace ccode= 437 if country=="Cote d'Ivoire"
replace ccode= 437 if country=="Cote D'Ivoire"
replace ccode= 437 if country=="CÃ´te d'Ivoire"
replace ccode= 437 if country=="CâˆšÂ¥te d'Ivoire"
replace ccode=437 if country=="Cote d'Ivoire"
replace ccode = 437 if country=="Cote D Ivoire"
replace ccode= 344 if country=="Croatia"
replace ccode= 344 if country=="Yugoslavia Croatia"
replace ccode= 40 if country=="Cuba"
replace ccode= 352 if country=="Cyprus"
replace ccode= 352 if country=="Cyprus (Greek)"
replace ccode= 316 if country=="Czech Republic"
replace ccode= 316 if country=="Czechia" & year>=1993
replace ccode= 316 if country=="Czech"
replace ccode= 316 if country=="Czech Rep."
replace ccode= 316 if country=="Czech Rep,"
replace ccode= 315 if country=="Czechoslavakia"
replace ccode= 315 if country=="Czechia" & year<1993
replace ccode= 315 if country=="Czechoslovakia"
replace ccode= 390 if country=="Denmark"
replace ccode= 522 if country=="Djibouti"
replace ccode= 54 if country=="Dominica"
replace ccode= 42 if country=="Dominican Republic"
replace ccode= 42 if country=="Dominacan Republic"
replace ccode= 42 if country=="Dominican Rep."
replace ccode= 42 if country=="Dominican Rep"
replace ccode= 42 if country=="Dominican"
replace ccode= 42 if country=="Dom. Rep."
replace ccode= 860 if country=="Timor"
replace ccode= 860 if country=="Timor Lest"
replace ccode= 860 if country=="Timor-Leste"
replace ccode= 860 if country=="East Timor"
replace ccode= 860 if country=="Timor Leste"
replace ccode= 130 if country=="Ecuador"
replace ccode= 651 if country=="Egypt"
replace ccode= 651 if country=="Egypt, Arab Rep."
replace ccode=651 if country=="Egypt, Arab Rep."
replace ccode=651 if country=="Egypt Arab Rep."
replace ccode= 92 if country=="El Salvador"
replace ccode= 411 if country=="Equatorial Guinea"
replace ccode= 411 if country=="Eq. Guinea"
replace ccode= 531 if country=="Eritrea"
replace ccode= 366 if country=="Estonia"
replace ccode= 530 if country=="Ethiopia"
replace ccode= 950 if country=="Fiji"
replace ccode= 375 if country=="Finland"
replace ccode= 220 if country=="France"
replace ccode= 481 if country=="Gabon"
replace ccode= 420 if country=="Gambia"
replace ccode= 420 if country=="Gambia, The"
replace ccode= 420 if country=="The Gambia"
replace ccode= 372 if country=="Georgia"
replace ccode= 255 if country=="Germany"
replace ccode= 255 if country=="Germany, United"
replace ccode= 255 if country=="Prussia"
replace ccode= 265 if country=="German Democratic Rep."
replace ccode= 265 if country=="East Germany"
replace ccode= 265 if country=="Germany, East"
replace ccode= 265 if country=="Germany East"
replace ccode= 265 if country=="German, East"
replace ccode= 265 if country=="German Democratic Republic"
replace ccode= 265 if country=="East Germany (GDR)"
replace ccode= 265 if country=="Germany, E. "
replace ccode= 265 if country=="GDR"
replace ccode= 260 if country=="German Federal Republic"
replace ccode= 260 if country=="Federal Republic of Germany"
replace ccode= 260 if country=="Federal Republic of Germany"
replace ccode= 260 if country=="Germany, W. "
replace ccode= 260 if country=="FRG/Germany"
replace ccode= 260 if country=="Germany, West"
replace ccode= 260 if country=="German West"
replace ccode= 260 if country=="Germany West"
replace ccode= 452 if country=="Ghana"
replace ccode=  99 if country=="Great Colombia"
replace ccode=  99 if country=="Gran Colombia"
replace ccode= 350 if country=="Greece"
replace ccode= 55 if country=="Grenada"
replace ccode= 90 if country=="Guatemala"
replace ccode= 90 if country=="Guatamala"
replace ccode= 438 if country=="Guinea"
replace ccode= 438 if country=="Republic of Guinea"
replace ccode= 404 if country=="Guinea-Bissau"
replace ccode= 404 if country=="Guinea Bissau"
replace ccode= 404 if country=="Guinea?Bissau"
replace ccode= 404 if country=="Guinea-Bissaau"
replace ccode= 110 if country=="Guyana"
replace ccode= 41 if country=="Haiti"
replace ccode= 240 if country=="Hanover"
replace ccode= 273 if country=="Hesse Electoral"
replace ccode= 273 if country=="Hesse-Kassel (Electoral)"
replace ccode= 275 if country=="Hesse Grand Ducal"
replace ccode= 275 if country=="Hesse-Darmstadt (Ducal)"
replace ccode= 91 if country=="Honduras"
replace ccode= 310 if country=="Hungary"
replace ccode= 395 if country=="Iceland"
replace ccode= 750 if country=="India"
replace ccode= 850 if country=="Indonesia"
replace ccode= 850 if country=="indonesia"
replace ccode= 630 if country=="Iran"
replace ccode= 630 if country=="Iran, Islamic Republic of"
replace ccode= 630 if country=="Islamic Republic of Iran"
replace ccode= 630 if country=="Iran, I.R. of"
replace ccode= 630 if country=="Iran, Islamic Rep."
replace ccode= 630 if country=="Iran (Islamic Republic of)"
replace ccode= 645 if country=="Iraq"
replace ccode= 205 if country=="Ireland"
replace ccode= 666 if country=="Israel"
replace ccode= 325 if country=="Italy"
replace ccode= 51 if country=="Jamaica"
replace ccode= 51 if country=="Jamaice"
replace ccode= 740 if country=="Japan"
replace ccode= 663 if country=="Jordan"
replace ccode= 705 if country=="Kazakhstan"
replace ccode= 705 if country=="Kazakhastan"
replace ccode= 501 if country=="Kenya"
replace ccode= 946 if country=="Kiribati"
replace ccode= 730 if country=="Korea"
replace ccode= 731 if country=="Korea, Dem. People's Rep."
replace ccode= 731 if country=="Korea, Democratic Republic"
replace ccode= 731 if country=="Korea, Dem. Rep."
replace ccode= 731 if country=="North Korea"
replace ccode= 731 if country=="Korea, North"
replace ccode= 731 if country=="Korea North"
replace ccode= 731 if country=="Korea, Peoples Republic of"
replace ccode= 731 if country=="Korea DPR (N)"
replace ccode= 731 if country=="PRK"
replace ccode= 731 if country=="Democratic People's Republic of Korea"
replace ccode= 731 if country=="Korea (North)"
replace ccode= 731 if country=="Korea, Democratic People's Republic of"
replace ccode= 731 if country=="Korea, Dem. Rep."
replace ccode= 731 if country=="Korea, Dem. Peopleâ€™s Rep."
replace ccode= 732 if country=="Korea, Republic of"
replace ccode= 732 if country=="Korea Republic"
replace ccode= 732 if country=="Republic of Korea"
replace ccode= 732 if country=="Korea, Republic Of"
replace ccode= 732 if country=="Korea, Rep."
replace ccode= 732 if country=="South Korea"
replace ccode= 732 if country=="Korea, South"
replace ccode= 732 if country=="Korea South"
replace ccode= 732 if country=="ROK"
replace ccode= 732 if country=="Korea (South)"
replace ccode= 732 if country=="KoreaÂ¬â€ (South)"
replace ccode=732 if country=="Korea, Rep."
replace ccode=732 if country=="Korea Rep. (S)"
replace ccode= 347 if country=="Kosovo"
replace ccode= 690 if country=="Kuwait"
replace ccode=703 if country=="Kyrgyz Republic"
replace ccode=703 if country=="Kyrgyzstan"
replace ccode= 703 if country=="Kirgizia"
replace ccode= 812 if country=="Laos"
replace ccode= 812 if country=="Lao People's Democratic Republic"
replace ccode= 812 if country=="Laos PDR"
replace ccode= 812 if country=="Lao PDR"
replace ccode = 812 if country=="Lao People S Dem.Rep"
replace ccode= 367 if country=="Latvia"
replace ccode= 660 if country=="Lebanon"
replace ccode= 570 if country=="Lesotho"
replace ccode= 450 if country=="Liberia"
replace ccode= 620 if country=="Libya"
replace ccode= 620 if country=="Libyan Arab Jamahiriya"
replace ccode= 620 if country=="Libyan Arab Jamahiriy"
replace ccode= 223 if country=="Liechtenstein"
replace ccode= 223 if country=="Liechenstein"
replace ccode= 368 if country=="Lithuania"
replace ccode= 212 if country=="Luxembourg"
replace ccode= 212 if country=="Luxemburg"
replace ccode= 343 if country=="Macedonia"
replace ccode= 343 if country=="Macedonia FYR"
replace ccode= 343 if country=="Macedonia, FYR"
replace ccode = 343 if country=="Macedonia, Fyr"
replace ccode = 343 if country=="The former Yugoslav Republic of Macedonia"
replace ccode = 343 if country=="The Former Yugoslav Republic of Macedonia"
replace ccode = 343 if country=="Macedonia, the Former Yugoslav Republic of"
replace ccode = 343 if country=="North Macedonia"
replace ccode = 343 if country=="Rep. of North Macedonia"
replace ccode = 343 if country=="Republic of North Macedonia"
replace ccode = 343 if country=="Macedonia, Republic of"
replace ccode= 580 if country=="Malagasy"
replace ccode= 580 if country=="Madagascar"
replace ccode= 553 if country=="Malawi"
replace ccode= 820 if country=="Malaysia"
replace ccode= 781 if country=="Maldive Islands"
replace ccode= 781 if country=="Maldives"
replace ccode= 432 if country=="Mali"
replace ccode= 432 if country=="Republic of Mali"
replace ccode= 338 if country=="Malta"
replace ccode= 983 if country=="Marshall Islands"
replace ccode= 435 if country=="Mauritania"
replace ccode= 590 if country=="Mauritius"
replace ccode= 280 if country=="Meckelnburg Schwerin"
replace ccode= 280 if country=="Meckelnburg-Schwerin"
replace ccode= 70 if country=="Mexico"
replace ccode= 987 if country=="Federated States of Micronesia"
replace ccode= 987 if country=="Micronesia, Federated States of"
replace ccode= 987 if country=="Micronesia (Federated States of)"
replace ccode=987 if country=="Micronesia, Fed. Sts."
replace ccode=987 if country=="Micronesia"
replace ccode = 987 if country=="Micronesia, Fed.Sts."
replace ccode= 332 if country=="Modena"
replace ccode= 359 if country=="Moldova"
replace ccode= 359 if country=="Moldova, Republic Of"
replace ccode= 359 if country=="Republic of Moldova"
replace ccode= 221 if country=="Monaco"
replace ccode= 712 if country=="Mongolia"
replace ccode= 341 if country=="Montenegro"
replace ccode = 341 if country=="Montenegro, Rep. Of"
replace ccode= 600 if country=="Morocco"
replace ccode= 541 if country=="Mozambique"
replace ccode= 775 if country=="Myanmar"
replace ccode= 775 if country=="Myanmar (Burma)"
replace ccode= 775 if country=="Myanmar/Burma"
replace ccode= 775 if country=="Burma"
replace ccode= 775 if country=="Burma (Myanmar)"
replace ccode= 775 if country=="Burma/Myanmar"
replace ccode= 565 if country=="Namibia"
replace ccode= 970 if country=="Nauru"
replace ccode= 790 if country=="Nepal"
replace ccode= 210 if country=="Netherlands"
replace ccode = 210 if country=="Netherland"
replace ccode= 920 if country=="New Zealand"
replace ccode= 93 if country=="Nicaragua"
replace ccode= 436 if country=="Niger"
replace ccode= 475 if country=="Nigeria"
replace ccode= 385 if country=="Norway"
replace ccode= 698 if country=="Oman"
replace ccode= 564 if country=="Orange Free State"
replace ccode= 770 if country=="Pakistan"
replace ccode= 986 if country=="Palau"
replace ccode= 95 if country=="Panama"
replace ccode= 327 if country=="Papal States"
replace ccode= 910 if country=="Papua New Guinea"
replace ccode= 910 if country=="Papau New Guinea"
replace ccode= 910 if country=="Papua New Guin."
replace ccode= 910 if country=="Papua NG"
replace ccode= 910 if country=="P. N. Guinea"
replace ccode= 150 if country=="Paraguay"
replace ccode= 335 if country=="Parma"
replace ccode= 135 if country=="Peru"
replace ccode= 840 if country=="Philippines"
replace ccode= 290 if country=="Poland"
replace ccode= 235 if country=="Portugal"
replace ccode= 6 if country=="Puerto Rico"
replace ccode= 6 if country=="Pueto Rico"
replace ccode= 694 if country=="Qatar"
replace ccode= 360 if country=="Rumania"
replace ccode= 360 if country=="Romania"
replace ccode= 365 if country=="Russia"
replace ccode= 365 if country=="Russian Federation"
replace ccode= 365 if country=="U.S.S.R."
replace ccode= 365 if country=="USSR"
replace ccode=365 if country=="Soviet Union"
replace ccode= 517 if country=="Rwanda"
replace ccode= 60 if country=="Saint Kitts and Nevis"
replace ccode= 60 if country=="St.Kitts& Nevis"
replace ccode= 60 if country=="St.Kitts&"
replace ccode= 60 if country=="St. Kitts And Nevis"
replace ccode=60 if country=="St. Kitts and Nevis"
replace ccode=60 if country=="St. Kitts & Nevis"
replace ccode= 56 if country=="Saint Lucia"
replace ccode= 56 if country=="St.Lucia"
replace ccode=56 if country=="St. Lucia"
replace ccode= 57 if country=="Saint Vincent and the Grenadines"
replace ccode= 57 if country=="St. Vincent and the Grenadines"
replace ccode= 57 if country=="St.Vincent & Grens."
replace ccode= 57 if country=="St. Vincent and the Grenadines"
replace ccode= 57 if country=="St.Vincent & G."
replace ccode= 57 if country=="St.Vincent"
replace ccode= 57 if country=="St. Vincent and the Gren"
replace ccode= 57 if country=="St. Vincent and the Grenadines"
replace ccode= 57 if country=="St.Vincent & Grenadines"
replace ccode= 57 if country=="St. Vincent"
replace ccode= 57 if country=="St. Vincent & Grens."
replace ccode= 990 if country=="Samoa"
replace ccode= 331 if country=="San Marino"
replace ccode= 403 if country=="Sao Tome & Principe"
replace ccode= 403 if country=="Sao Tome and Principe"
replace ccode= 324 if country=="Sardinia"
replace ccode= 670 if country=="Saudi Arabia"
replace ccode= 269 if country=="Saxony"
replace ccode= 433 if country=="Senegal"
replace ccode= 591 if country=="Seychelles"
replace ccode= 451 if country=="Sierra Leone"
replace ccode= 830 if country=="Singapore"
replace ccode= 317 if country=="Slovakia"
replace ccode= 317 if country=="Slovak Republic"
replace ccode= 349 if country=="Slovenia"
replace ccode= 940 if country=="Solomon Islands"
replace ccode= 940 if country=="Solomon Island"
replace ccode= 940 if country=="Soloman Island"
replace ccode= 940 if country=="Soloman Is."
replace ccode= 940 if country=="Solomon Is."
replace ccode= 520 if country=="Somalia"
replace ccode= 560 if country=="South Africa"
replace ccode= 560 if country=="South africa"
replace ccode= 560 if country=="S. Africa"
replace ccode= 625 if country=="Sudan"
replace ccode= 625 if country=="Sudan North"
replace ccode= 625 if country=="Sudan-North"
replace ccode= 626 if country=="South Sudan"
replace ccode= 626 if country=="Sudan South"
replace ccode= 626 if country=="Sudan-South"
replace ccode= 230 if country=="Spain"
replace ccode= 780 if country=="Sri Lanka"
replace ccode= 780 if country=="Sri Lanka (JVP)"
replace ccode= 780 if country=="Sri Lanka (Ceylon)"
replace ccode= 115 if country=="Suriname"
replace ccode= 572 if country=="Swaziland"
replace ccode=572 if country=="Eswatini"
replace ccode= 380 if country=="Sweden"
replace ccode= 225 if country=="Switzerland"
replace ccode= 652 if country=="Syria"
replace ccode= 652 if country=="Syrian Arab Republic"
replace ccode= 652 if country=="Syrian Arab RepublicÂ¬â€ (Syria)"
replace ccode= 713 if country=="Taiwan"
replace ccode= 702 if country=="Tadzhikistan"
replace ccode= 702 if country=="Tajikistan"
replace ccode= 510 if country=="Tanzania"
replace ccode= 510 if country=="Tanzania, United Republic of"
replace ccode= 510 if country=="United Republic of Tanzania"
replace ccode= 510 if country=="United Republic of Tanzania: Mainland"
replace ccode= 800 if country=="Thailand"
replace ccode= 711 if country=="Tibet"
replace ccode= 461 if country=="Togo"
replace ccode= 955 if country=="Tonga"
replace ccode= 563 if country=="Transvaal"
replace ccode= 52 if country=="Trinidad"
replace ccode= 52 if country=="Trinidad & Tob."
replace ccode= 52 if country=="Trinidad & Tobago"
replace ccode= 52 if country=="Trinidad &Tobago"
replace ccode= 52 if country=="Trinidad-Tobago"
replace ccode= 52 if country=="Trinidad and Tobago"
replace ccode= 52 if country=="Trinidad/Tobago"
replace ccode= 616 if country=="Tunisia"
replace ccode= 640 if country=="Turkey"
replace ccode= 640 if country=="Turkiye"
replace ccode= 701 if country=="Turkmenistan"
replace ccode= 337 if country=="Tuscany"
replace ccode= 947 if country=="Tuvalu"
replace ccode= 329 if country=="Two Sicilies"
replace ccode= 696 if country=="United Arab Emirates"
replace ccode= 696 if country=="United Arab Em."
replace ccode= 696 if country=="UAE"
replace ccode= 500 if country=="Uganda"
replace ccode= 369 if country=="Ukraine"
replace ccode= 200 if country=="United Kingdom"
replace ccode= 200 if country=="UK"
replace ccode= 200 if country=="United Kingdom of Great Britain and Northern Ireland"
replace ccode= 89 if country=="United Province CA"
replace ccode= 89 if country=="United Provinces of Central America"
replace ccode= 2 if country=="United States of America"
replace ccode= 2 if country=="US"
replace ccode= 2 if country=="USA"
replace ccode= 2 if country=="United States"
replace ccode= 165 if country=="Uruguay"
replace ccode= 704 if country=="Uzbekistan"
replace ccode= 935 if country=="Vanuatu"
replace ccode= 327 if country=="Vatican"
replace ccode= 101 if country=="Venezuela"
replace ccode= 101 if country=="Venezuela, RB"
replace ccode= 101 if country=="Venezuela (Bolivarian Republic of)"
replace ccode= 101 if country=="VenezuelaÂ¬â€ (Bolivarian Republic)"
replace ccode= 816 if country=="Vietnam, Democratic Rep."
replace ccode= 816 if country=="Viet Nam"
replace ccode=816 if country=="Vietnam"
replace ccode= 816 if country=="N. Vietnam"
replace ccode= 816 if country=="Vietnam, N."
replace ccode= 816 if country=="Vietnam, North"
replace ccode= 816 if country=="Vietnam North"
replace ccode= 817 if country=="Vietnam, Republic of"
replace ccode= 817 if country=="Republic of Vietnam"
replace ccode= 817 if country=="S. Vietnam"
replace ccode= 817 if country=="Vietnam, S."
replace ccode= 817 if country=="South Vietnam"
replace ccode= 817 if country=="Vietnam, South"
replace ccode= 271 if country=="Wuerttemburg"
replace ccode= 678 if country=="Yemen Arab Republic"
replace ccode= 678 if country=="Yemen AR"
replace ccode= 678 if country=="Yemen (AR)"
replace ccode= 678 if country=="Yemen, N.Arab"
replace ccode= 678 if country=="North Yemen"
replace ccode= 678 if country=="Yemen, N."
replace ccode= 678 if country=="Yemen North"
replace ccode= 678 if country=="Yemen Arab Republic; N. Yemen"
replace ccode= 679 if country=="Yemen"
replace ccode= 679 if country=="Yemen"
replace ccode= 679 if country=="Yemen Rep."
replace ccode= 679 if country=="Yemen, Rep."
replace ccode = 679 if country=="Yemen, Republic Of"
replace ccode= 680 if country=="S. Yemen"
replace ccode= 680 if country=="Yemen, S."
replace ccode= 680 if country=="Yemen South"
replace ccode= 680 if country=="Yemen People's Republic"
replace ccode= 680 if country=="Yemen PR"
replace ccode= 680 if country=="South Yemen"
replace ccode= 680 if country=="Yemen (PDR)"
replace ccode= 680 if country=="Yemen PDR (South)"
replace ccode = 680 if country=="Yemen, P.D. Rep."
replace ccode = 680 if country=="Yemen People's Republic; S. Yemen"
replace ccode=345 if country=="Yugoslavia, Fed. Rep."
replace ccode= 345 if country=="Yugoslavia/Serbia"
replace ccode= 345 if country=="Serbia"
replace ccode= 345 if country=="Serbia and Montenegro"
replace ccode= 345 if country=="Yugoslavia"
replace ccode= 345 if country=="Yugoslavia FPR"
replace ccode= 345 if country=="Yugoslavia FR"
replace ccode= 345 if country=="Serbia & Montenegro"
replace ccode= 551 if country=="Zambia"
replace ccode= 511 if country=="Zanzibar"
replace ccode= 552 if country=="Zimbabwe"
replace ccode= 552 if country=="Zimbabwe (Rhodesia)"
replace ccode= 552 if country=="Rhodesia"

/*mark missing*/
replace ccode=-999 if country=="Abu Dhabi"
replace ccode=-999 if country=="American Samoa"
replace ccode=-999 if country=="Anguilla"
replace ccode=-999 if country=="Aruba"
replace ccode=-999 if country=="Azores"
replace ccode=-999 if country=="Bermuda"
replace ccode=-999 if country=="Canary Islands"
replace ccode=-999 if country=="Cayman Islands"
replace ccode=-999 if country=="Channel Islands"
replace ccode=-999 if country=="Christmas Islands"
replace ccode=-999 if country=="Cocos Islands"
replace ccode=-999 if country=="Cook Islands"
replace ccode=-999 if country=="Cyprus  (Turkish)"
replace ccode=-999 if country=="Cyprus (Turkey)"
replace ccode=-999 if country=="Turk Cyprus"
replace ccode=-999 if country=="Easter Island"
replace ccode=-999 if country=="Faeroe Islands"
replace ccode=-999 if country=="Falkland Islands"
replace ccode=-999 if country=="Falkland Islands (Malvinas)"
replace ccode=-999 if country=="French Polynesia"
replace ccode=-999 if country=="Gibraltar"
replace ccode=-999 if country=="Greenland"
replace ccode=-999 if country=="Guadeloupe"
replace ccode=-999 if country=="Guam"
replace ccode=-999 if country=="Hong Kong"
replace ccode=-999 if country=="Hong Kong SAR, China"
replace ccode=-999 if country=="China: Hong Kong SAR"
replace ccode=-999 if country=="Guyana, French"
replace ccode=-999 if country=="Isle of Man"
replace ccode=-999 if country=="Leeward Islands"
replace ccode=-999 if country=="Macao"
replace ccode=-999 if country=="China: Macao SAR"
replace ccode=-999 if country=="Madeira"
replace ccode=-999 if country=="Martinique"
replace ccode=-999 if country=="Mayotte"
replace ccode=-999 if country=="Montserrat"
replace ccode=-999 if country=="Netherlands Antilles"
replace ccode=-999 if country=="New Caledonia"
replace ccode=-999 if country=="New Zealand dependencies"
replace ccode=-999 if country=="Niue"
replace ccode=-999 if country=="Norfolk Islands"
replace ccode=-999 if country=="Northern Marianas Islands"
replace ccode=-999 if country=="Pacific Islands (Trust territory)"
replace ccode=-999 if country=="Palestinian Administration Areas"
replace ccode=-999 if country=="Panama Canal Zone"
replace ccode=-999 if country=="Reunion"
replace ccode=-999 if country=="Ryukyus"
replace ccode=-999 if country=="Saint Helena"
replace ccode=-999 if country=="Saint Pierre & Miquelon"
replace ccode=-999 if country=="Tokelau"
replace ccode=-999 if country=="Transkei"
replace ccode=-999 if country=="Turks & Caicos Islands"
replace ccode=-999 if country=="Venda"
replace ccode=-999 if country=="Virgin Islands (UK)"
replace ccode=-999 if country=="British Virgin Islands"
replace ccode=-999 if country=="Virgin Islands (US)"
replace ccode=-999 if country=="Virgin Islands (U.S.)"
replace ccode=-999 if country=="U. S. Virgin Islands"
replace ccode=-999 if country=="Wallis & Futuna"
replace ccode= 990 if country=="Western Samoa"
replace ccode= 990 if country=="W. Samoa"
replace ccode= 990 if country=="West Samoa"
replace ccode=-999 if country=="Windward Islands"

/*fix discrepancies w/ Polity*/
gen ccode_polity=.
label var ccode_p "Polity ccodes (if different than COW)"
capture replace ccode_polity=255 if country=="Germany" & year==1990
capture replace ccode_polity=255 if country=="Germany, United" & year==1990
replace ccode_polity=341 if country=="Kosovo"
replace ccode_polity=348 if country=="Montenegro"
replace ccode_polity=348 if country=="Montenegro, Rep. Of"
replace ccode_polity=818 if country=="Vietnam"
capture replace ccode_polity=818 if country=="Vietnam" & year>=1976
capture replace ccode_polity=342 if ccode==345 & year>=1830 & year<=1920
capture replace ccode_polity=347 if ccode==345 & year>=1991 & year<=2002
capture replace ccode_polity=342 if ccode==345 & year>=2006
capture replace ccode_polity=529 if ccode==530 & year>=1993
replace ccode_polity=341 if ccode==347
capture replace ccode_polity=769 if ccode==770 & year<=1971
capture replace ccode_polity=364 if ccode==365 & year>=1922 & year<=1991
capture replace ccode_polity=525 if ccode==626
replace ccode_polity=525 if country=="South Sudan"
replace ccode_polity=525 if country=="Sudan South"
replace ccode_polity=525 if country=="Sudan-South"
capture replace ccode_polity=626 if ccode==625 & year>=2011
replace ccode_polity=626 if country=="North Sudan"
replace ccode_polity=626 if country=="Sudan North"
replace ccode_polity=626 if country=="Sudan-North"

/*fix discrepancies w/ Gleditsch/Ward*/
gen ccode_gw=.
label var ccode_g "Gleditsch/Ward ccodes (if different than COW)"
capture replace ccode_gw=260 if ccode==255 & year>=1949
capture replace ccode_gw=340 if ccode==345 & year>=1878 & year<=1915
capture replace ccode_gw=340 if ccode==345 & year>=2006
capture replace ccode_gw=815 if country=="Vietnam" & year>=1816 & year<=1893

*Updated on 03/05/12 with World Bank WDI country names (thanks to Leah Windsor from Ole Miss)
*Updated on 12/04/13 w/ countries from the UN; http://unstats.un.org/unsd/methods/m49/m49alpha.htm
*Updated on 05/21/15 w/ spellings from the most recent polity update (thanks to Peter White from U Maryland)
*Updated on 07/01/15 w/ spellings from the Geddes/Wright/Frantz dataset (thanks again to Peter White from U Maryland)
*Updated on 09/08/15 w/ spellings from Penn World Tables (thanks to Curtis Bell from One Earth Future)
*Updated on 02/08/16 w/ spellings from Penn World Tables (thanks to Joeri Smits from NADEL Center for Development and Cooperation)
*Updated on 01/26/17 w/ spellings from James, et al. 2012. 'Developing a comprehensive time series of GDP per capita for 210 countries from 1950 to 2015.' Population Health Metrics 10:12.
*Updated on 05/30/17 w/ some descrepancies between ICOW and G&W (see notes below); (thanks to Brendan Apfeld from Univ of Texas)
*Updated on 10/13/20 w/ North Macedonia replacing Macedonia; (thanks to Holley Hansen from Oklahoma State)
*Updated on 06/15/21 w/ "The Gambia" (thanks to Phillip Nelson from Univ of Warwick)
*Updated on 08/11/26 w/ "Turkiye" and "Czechia" (thanks to Holley Hansen from Oklahoma State)
